src/Entity/User.php
<?php
namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

// /src/Entity/User.php



/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @ORM\Table(name="user")
 * @UniqueEntity(fields="email", message="Email déjà pris")
 * @UniqueEntity(fields="username", message="Username déjà pris")
 */
class User implements UserInterface, \Serializable
{
    /**
     * @var int
     *
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;


    /**
     * @var string
     *
     * @ORM\Column(type="string", unique=true, length=50)
     * @Assert\NotBlank()
     */
    private $username;

    /**
     * @var string
     *
     * @ORM\Column(type="string", unique=true, length=50)
     * @Assert\NotBlank()
     * @Assert\Email()
     */
    private $email;

    /**
     * @var string
     *
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @var array
     *
     * @ORM\Column(type="text")
     */
    private $roles;


    /**
     * @ORM\GeneratedValue
     * @ORM\Column(type="string", nullable=true)
     */
    private $user_image;

    /**
     * @ORM\GeneratedValue
     * @ORM\Column(type="decimal", nullable=true)
     */
    private $user_etat;

    /**
     * @ORM\GeneratedValue
     * @ORM\Column(type="decimal", nullable=true)
     */
    private $user_jouees;

    /**
     * @ORM\GeneratedValue
     * @ORM\Column(type="decimal", nullable=true)
     */
    private $user_win;


    public function getId(): int
    {
        return $this->id;
    }


    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): void
    {
        $this->username = $username;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): void
    {
        $this->email = $email;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): void
    {
        $this->password = $password;
    }

    /**
     * Retourne les rôles de l'user
     */
     public function getRoles()
       {
          // Afin d'être sûr qu'un user a toujours au moins 1 rôle
           return json_decode($this->roles);
       }

       /**
        * @param $roles
        * @return $this
        */
       public function setRoles($roles)
       {
           $this->roles = $roles;
       }

    /**
     * @return mixed
     */
    public function getUserImage()
    {
        return $this->user_image;
    }

    /**
     * @param mixed $user_image
     */
    public function setUserImage($user_image)
    {
        $this->user_image = $user_image;
    }

    /**
     * @return mixed
     */
    public function getUserEtat()
    {
        return $this->user_etat;
    }

    /**
     * @param mixed $user_etat
     */
    public function setUserEtat($user_etat)
    {
        $this->user_etat = $user_etat;
    }

    /**
     * @return mixed
     */
    public function getUserJouees()
    {
        return $this->user_jouees;
    }

    /**
     * @param mixed $user_jouees
     */
    public function setUserJouees($user_jouees)
    {
        $this->user_jouees = $user_jouees;
    }

    /**
     * @return mixed
     */
    public function getUserWin()
    {
        return $this->user_win;
    }

    /**
     * @param mixed $user_win
     */
    public function setUserWin($user_win)
    {
        $this->user_win = $user_win;
    }

    /**
     * Retour le salt qui a servi à coder le mot de passe
     *
     * {@inheritdoc}
     */
    public function getSalt(): ?string
    {
// See "Do you need to use a Salt?" at https://symfony.com/doc/current/cookbook/security/entity_provider.html
// we're using bcrypt in security.yml to encode the password, so
// the salt value is built-in and you don't have to generate one

        return null;
    }

    /**
     * Removes sensitive data from the user.
     *
     * {@inheritdoc}
     */
    public function eraseCredentials(): void
    {
// Nous n'avons pas besoin de cette methode car nous n'utilions pas de plainPassword
// Mais elle est obligatoire car comprise dans l'interface UserInterface
// $this->plainPassword = null;
    }

    /**
     * {@inheritdoc}
     */
    public function serialize(): string
    {
        return serialize([$this->id, $this->username, $this->password]);
    }

    /**
     * {@inheritdoc}
     */
    public function unserialize($serialized): void
    {
        [$this->id, $this->username, $this->password] = unserialize($serialized, ['allowed_classes' => false]);
    }
}
?>

src/Form/UserType.php
<?php
// /src/Form/UserType.php
namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\RepeatedType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('email', EmailType::class)
            ->add('username', TextType::class)
            ->add('password', RepeatedType::class, array(
                'type' => PasswordType::class,
                'first_options'  => array('label' => 'Mot de passe'),
                'second_options' => array('label' => 'Répéter le mot de passe'),
            ))
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => User::class,
        ));
    }
}

src/Controller/UserController.php
<?php
namespace App\Controller;


use App\Entity\User;
use App\Entity\Amis;

use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;



class UserController extends Controller
{
    private $passwordEncoder;

    public function __construct(UserPasswordEncoderInterface $passwordEncoder)
    {
        $this->passwordEncoder = $passwordEncoder;
    }


    /**
     * @Route("/user", name="user")
     */
    public function user()
    {
        $joueur = $this->getUser();
        return $this->render('User/index.html.twig', ['joueur' => $joueur]);
    }

    /**
     * @Route("/user/profil", name="profil")
     */
    public function profil()
    {
        $joueur = $this->getUser();

        $joueurs = $this->getDoctrine()->getRepository("App:User");
        $joueurs = $joueurs->findAll();

        $amis = $this->getDoctrine()->getRepository("App:Amis");
        $amis = $amis->findAll();

        $rang = $this->getDoctrine()->getRepository("App:User");
        $rang = $rang->findBy(array(), array('user_win' => 'desc'),5,0);
        return $this->render('User/profil.html.twig', ['joueur' => $joueur, 'joueurs' => $joueurs, 'rang' => $rang, 'amis' => $amis]);
    }

    /**
     * @Route("/user/modifier/avatar", name="modifier_avatar")
     */
    public function modifier_avatar()
    {
        $joueur = $this->getUser();
        return $this->render('User/modifier_avatar.html.twig', ['joueur' => $joueur]);
    }

    /**
     * @Route("/update_avatar", name="new_avatar")
     */
    public function new_avatar(Request $request)
    {
        $new_avatar = $request->request->get('avatar');
        $user = $this->getUser();
        if($user) {
            $id = $user->getId();
        } else {
            $id = "Pas d'Id";
        }
        $entityManager = $this->getDoctrine()->getManager();
        $user_image = $entityManager->getRepository(User::class)->find($id);
        if (!$user_image) {
            throw $this->createNotFoundException(
                'No avatar found for id '.$id
            );
        }
        $user_image->setUserImage($new_avatar);
        $entityManager->persist($user_image);
        $entityManager->flush();
        return $this->redirectToRoute('profil');
    }

    /**
     * @Route("/user/modifier/informations", name="modifier_informations")
     */
    public function modifier_informations()
    {
        $joueur = $this->getUser();

        $joueurs = $this->getDoctrine()->getRepository("App:User");
        $joueurs = $joueurs->findAll();

        $limit = $this->getDoctrine()->getRepository("App:Chat");
        $limit = $limit->findBy(array(), array('id' => 'desc'),1,0);
        $limit = $limit[0]->getId();
        $limit = $limit - 5;

        $chat = $this->getDoctrine()->getRepository("App:Chat");
        $chat = $chat->findBy(array(), array('id' => 'ASC'),5, $limit);

        return $this->render('User/modifier.html.twig', ['joueur' => $joueur, 'joueurs' => $joueurs, 'chat'=> $chat]);
    }

    /**
     * @Route("/update_username", name="update_username")
     */
    public function new_username(Request $request){
        $new_username = $request->request->get('username');
        $user = $this->getUser();
        if($user) {
            $id = $user->getId();
        } else {
            $id = "Pas d'Id";
        }
        $entityManager = $this->getDoctrine()->getManager();
        $username = $entityManager->getRepository(User::class)->find($id);
        if (!$username) {
            throw $this->createNotFoundException(
                'No username found for id '.$id
            );
        }
        $username->setUsername($new_username);
        $entityManager->persist($username);
        $entityManager->flush();
        return $this->redirectToRoute('profil');
    }
    /**
     * @Route("/update_email", name="update_email")
     */
    public function new_email(Request $request){
        $new_email = $request->request->get('email');
        $user = $this->getUser();
        if($user) {
            $id = $user->getId();
        } else {
            $id = "Pas d'Id";
        }
        $entityManager = $this->getDoctrine()->getManager();
        $email = $entityManager->getRepository(User::class)->find($id);
        if (!$email) {
            throw $this->createNotFoundException(
                'No email found for id '.$id
            );
        }
        $email->setEmail($new_email);
        $entityManager->persist($email);
        $entityManager->flush();
        return $this->redirectToRoute('profil');
    }

    /**
     * @Route("/update_password", name="update_password")
     */
    public function new_password(Request $request, UserPasswordEncoderInterface $passwordEncoder)
    {
        $password_send = $request->request->get('premier');
        $password_send1 = $request->request->get('deuxieme');

        if ($password_send != $password_send1) {
            return $this->redirectToRoute('user_fail');
        }
        else{
            $user = $this->getUser();
            if ($user) {
                $id = $user->getId();
            } else {
                $id = "Pas d'Id";
            }
            $new_password = $passwordEncoder->encodePassword($user, $password_send);
            $entityManager = $this->getDoctrine()->getManager();
            $password = $entityManager->getRepository(User::class)->find($id);
            if (!$password) {
                throw $this->createNotFoundException(
                    'No username found for id ' . $id
                );
            }
            $password->setPassword($new_password);
            $entityManager->persist($password);
            $entityManager->flush();
            return $this->redirectToRoute('profil');
        }
    }

    /**
     * @Route("/user/rechercher/{username}", name="rechercher_joueur")
     */
    public function rechercher_joueur($username){
        $entityManager = $this->getDoctrine()->getManager();
        $users = $entityManager->getRepository("App:User")->findByUsername($username);
        return $this->render('User/search.html.twig', ['users'=>$users]);
    }
    /**
     * @Route("/user/joueur/{id}", name="joueur")
     */
    public function joueur($id){
        $joueur = $this->getUser();
        if($id != $joueur->getId()){
            $joueurs = $this->getDoctrine()->getRepository("App:User");
            $joueurs = $joueurs->findAll();

            $amis = $this->getDoctrine()->getRepository("App:Amis");
            $amis = $amis->findBy(['id_ami1' => $joueur->getId()]);

            $limit = $this->getDoctrine()->getRepository("App:Chat");
            $limit = $limit->findBy(array(), array('id' => 'desc'),1,0);
            $limit = $limit[0]->getId();
            $limit = $limit - 5;

            $chat = $this->getDoctrine()->getRepository("App:Chat");
            $chat = $chat->findBy(array(), array('id' => 'ASC'),5, $limit);

            return $this->render('User/joueur.html.twig', ['joueur' => $joueur, 'joueurs' => $joueurs, 'id' => $id, 'amis' => $amis, 'chat' => $chat]);
        }
        else{
            return $this->redirectToRoute('profil');
        }
    }
    /**
     * @Route("/user/ajouterami/{id}", name="ajouterami")
     */
    public function ajouterami($id){
        $joueur = $this->getUser();

        $amitie = new Amis();
        $amitie->setIdAmi1($joueur->getId());
        $amitie->setIdAmi2($id);
        $em = $this->getDoctrine()->getManager();
        $em->persist($amitie);
        $em->flush();

        $amitie = new Amis();
        $amitie->setIdAmi1($id);
        $amitie->setIdAmi2($joueur->getId());
        $em = $this->getDoctrine()->getManager();
        $em->persist($amitie);
        $em->flush();

        return $this->redirectToRoute('joueur', ['id' => $id]);
    }

    /**
     * @Route("/user/supprimerami/{id}", name="supprimerami")
     */
    public function supprimerami($id){
        $joueur = $this->getUser();

        $id = (int)$id;
        $amitie = $this->getDoctrine()->getRepository("App:Amis");
        $amitie = $amitie->findOneBy(['id_ami1' => $joueur->getId(), 'id_ami2' => $id]);
        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->remove($amitie);
        $entityManager->flush();

        $amitie = $this->getDoctrine()->getRepository("App:Amis");
        $amitie = $amitie->findOneBy(['id_ami1' => $id, 'id_ami2' => $joueur->getId()]);
        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->remove($amitie);
        $entityManager->flush();


        return $this->redirectToRoute('joueur', ['id' => $id]);
    }
}
?>

templates/User/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Bienvenue dans Halvel Battle
{% endblock %}

{% block style %}
    .bloc1{
    {% if app.user.roles == ["ROLE_ADMIN"] %}
        padding-top: 10vh !important;
    {% endif %}
    background-image: url({{ asset('img/fond.jpg') }});
    }
    #boutton{
    margin-top: 10vh;
    }
{% endblock %}

{% block bloc1 %}
    {% if app.user.roles == ["ROLE_ADMIN"] %}
        <a href="{{ path('admin') }}"><h2>Accéder au Back Office</h2></a>
    {% endif %}
    <div class="col-md-12">
        <img src="{{ asset('img/logo_blanc.png') }}" alt="Halvel Battle"/>
    </div>
    <div class="col-md-12" id="boutton">
        <a href="{{  path('nouvelle_partie') }}"><img src="{{ asset('img/jouer.png') }}" alt="Jouer"/></a>
    </div>

{% endblock %}

templates/User/joueur.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    {% for tjoueurs in joueurs %}
        {% if tjoueurs.Id == id %}
            Profil de {{ tjoueurs.Username }}
        {% endif %}
    {% endfor %}
{% endblock %}

{% block style %}
    .bloc1{
    background-image: url({{ asset('img/fond3.png') }});
    }
    #boutton{
    margin-top: 10vh;
    }
    img{
    width:8vw;
    text-align: left;
    }

    #modifier{
    margin:0px !important;
    text-align:center !important;
    }
    .actionjoueur{
        background-color: #181E2C;
        border-radius: 10px;
        float: left;
        width:18vw;
        height: 10vh;
        margin: 1vw;
        padding-top:3.5vh;
        cursor:pointer;
    }
    .actionjoueur:hover{
        background-color:#303851;
    }
    .actionjoueur p{
        text-align:center;
        font-size: 1.3em;
        font-family: 'Cinzel', serif;
        margin:0;
    }
    .chat{
        margin-top:0;
    }
{% endblock %}

{% block bloc1 %}
    {% for tjoueurs in joueurs %}
        {% if tjoueurs.Id == id %}
            <div class="col-md-7 colonne">
                <div id="infojoueurs">
                    <div id="img">
                        <img src="{{ asset(tjoueurs.UserImage) }}" alt="">
                    </div>
                    <div id="joueurs">
                        <h2>{{ tjoueurs.Username }}</h2>
                        <p>Nombre de parties jouées : {{ tjoueurs.UserJouees }}</p>
                        <p>Nombre de parties gagnées : {{ tjoueurs.UserWin }}</p>
                        <p>Nombre de parties perdues : {{ tjoueurs.userJouees - tjoueurs.UserWin }}</p>
                        {% if joueur.userJouees != 0 %}
                            <p>Ratio : {{ ((tjoueurs.UserWin / tjoueurs.userJouees)|round(2, 'floor'))*100 }}% de victoire</p>
                        {% endif %}
                    </div>
                </div>
                
                    {% set ok = 'none' %}
                    {% for ami in amis %}
                        {% if id == ami.IdAmi2 %}
                            <a href="{{ path("supprimerami", {'id': tjoueurs.Id}) }}"><div class="actionjoueur">
                                <p>Supprimer cet ami</p>
                            </div></a>
                            {% set ok = 'ok' %}
                        {% endif %}
                    {% endfor %}
                    {% if ok == 'none' %}
                        <a href="{{ path("ajouterami", {'id': tjoueurs.Id}) }}"><div class="actionjoueur">
                            <p>Ajouter en ami</p>
                        </div></a>
                    {% endif %}
                <a href="{{ path("creer2_partie", {'idadversaire': tjoueurs.Id}) }}">
                    <div class="actionjoueur">
                        <p>Défier</p>
                    </div>
                </a>

            </div>
        {% endif %}
    {% endfor %}
    <div class="col-md-4 colonne">
        <div class="chat">
            <div id="chat">
                <h2>Chat Global</h2>
                {% for message in chat %}

                    {% if message.PseudoId == joueur.Id %}
                        <div class="message">
                            <img class="avatars" src="{{ asset(joueur.UserImage)}}" alt=""><h5>Moi : </h5> <p>{{ message.MessageGlobal }}</p>
                            <br>
                        </div>

                    {% endif %}
                    {% for tjoueurs in joueurs %}
                        {% if message.PseudoId == tjoueurs.Id and message.PseudoId != joueur.Id  %}
                            <div class="message">
                                <img class="avatars" src="{{ asset(tjoueurs.UserImage)}}" alt=""><h5>{{ tjoueurs.Username }} : </h5><p>{{ message.MessageGlobal }}</p>
                                <br>
                            </div>
                        {% endif %}
                    {% endfor %}
                {% endfor %}
            </div>
            <input class="chatinput" type="text" placeholder="Votre message...">
            <input class="chatsubmit" type="submit" value="envoyer">
        </div>
    </div>
    <script>
        $(document).ready(function(){
            function envoyer(message){
                $.ajax({
                    url: "{{ path("new_message") }}",
                    method: 'post',
                    data: {'message': message}
                });
            }


            $('.chatsubmit').click(function() {
                message = $('.chatinput').val();
                envoyer(message);
                $('.chatinput').val("");
            });

            setInterval(function () {
                $("#chat").load("{{ path('chat') }}");
            }, 1000);
        });
    </script>
{% endblock %}

templates/User/modifier.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Modifier vos informations
{% endblock %}

{% block style %}
    .bloc1{
    background-image: url({{ asset('img/fond3.png') }});
    }
    #boutton{
    margin-top: 10vh;
    }
    img{
    width:8vw;
    text-align: left;
    }
    .chat{
        margin: 1%;
    }
{% endblock %}

{% block bloc1 %}

    <div class="col-md-4 info colonne">
        <div id="infojoueur">
            <div id="img">
                <a href="{{ path("modifier_avatar") }}"><img src="{{ asset(joueur.UserImage) }}" alt=""></a>
            </div>
            <div id="joueur">
                <h2>{{ joueur.Username }}</h2>
            </div>
        </div>


        <div id="stats">
            <h2>Statistiques</h2>
            <p>Nombre de parties jouées : {{ joueur.UserJouees }}</p>
            <p>Nombre de parties gagnées : {{ joueur.UserWin }}</p>
            <p>Nombre de parties perdues : {{ joueur.userJouees - joueur.UserWin }}</p>
            {% if joueur.userJouees != 0 %}
                <p>Ratio : {{ ((joueur.UserWin / joueur.userJouees)|round(1, 'floor'))*100 }}% de victoire</p>
            {% endif %}
        </div>
    </div>
    <div class="col-md-4 info section">

    <form method="post" action="{{ path('update_username') }}">
        <div>
            <h2 class="h2change">Changer de pseudo :</h2>
            <input class="forminput" type="text" value="{{ app.user.username }}" name="username" placeholder="Nouveau Pseudo">
            <input class="formsubmit" type="submit" value="Changer">
        </div>
    </form>

    <form method="post" action="{{ path('update_email') }}">
        <div>
            <h2 class="h2change">Changer d'email :</h2>
            <input class="forminput" type="email" value="{{ app.user.email }}" name="email" placeholder="Nouvel email">
            <input class="formsubmit" type="submit" value="Changer">
        </div>
    </form>

    <form method="post" action="{{ path('update_password') }}">
        <div>
            <h2 class="h2change">Changer de mot de passe :</h2>
            <input class="mdpforminput" type="password" name="premier" placeholder="Entrer nouveau mot de passe"><br>
            <input class="mdpforminput" type="password" name="deuxieme" placeholder="Répéter mot de passe">
            <input class="mdpformsubmit" type="submit" value="Changer">
        </div>
    </form>
    </div>
    <div class="col-md-4 colonne">
        <div class="chat">
            <div id="chat">
                <h2>Chat Global</h2>
                {% for message in chat %}

                    {% if message.PseudoId == joueur.Id %}
                        <div class="message">
                            <img class="avatars" src="{{ asset(joueur.UserImage)}}" alt=""><h5>Moi : </h5> <p>{{ message.MessageGlobal }}</p>
                            <br>
                        </div>

                    {% endif %}
                    {% for tjoueurs in joueurs %}
                        {% if message.PseudoId == tjoueurs.Id and message.PseudoId != joueur.Id  %}
                            <div class="message">
                                <img class="avatars" src="{{ asset(tjoueurs.UserImage)}}" alt=""><h5>{{ tjoueurs.Username }} : </h5><p>{{ message.MessageGlobal }}</p>
                                <br>
                            </div>
                        {% endif %}
                    {% endfor %}
                {% endfor %}
            </div>
            <input class="chatinput" type="text" placeholder="Votre message...">
            <input class="chatsubmit" type="submit" value="envoyer">
        </div>
    </div>
    <script>
        $(document).ready(function(){
            function envoyer(message){
                $.ajax({
                    url: "{{ path("new_message") }}",
                    method: 'post',
                    data: {'message': message}
                });
            }


            $('.chatsubmit').click(function() {
                message = $('.chatinput').val();
                envoyer(message);
                $('.chatinput').val("");
            });

            setInterval(function () {
                $("#chat").load("{{ path('chat') }}");
            }, 1000);
        });
    </script>
{% endblock %}

templates/User/profil.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Voici votre profil
{% endblock %}

{% block style %}
    .bloc1{
        background-image: url({{ asset('img/fond3.png') }});
    }
    #boutton{
        margin-top: 10vh;
    }
    img{
        width:8vw;
        text-align: left;
        float: left;
    }
    #modifier{
        text-align:center;
        margin:0;
    }
    #ami{
        height:6vh;
    }
    #searchbarre{
        display:none;
    }
    #inputsearch{
        margin-left: 4vw;
        height: 5vh;
        text-align: left;
        margin-top: 1vh;
        margin-bottom: 1vh;
        float: left;
        background-color: #151020;
        color: white;
        border: 0 solid;
        border-radius: 10px 0px 0px 10px;
        padding-left: 10px;
    }
    #submitsearch{
        height: 5vh;
        margin-top: 1vh;
        margin-bottom: 1vh;
        float:left;
        width: 8vw;
        background-color: #151020;
        color: white;
        border: 0px solid;
        border-radius: 0px 10px 10px 0px;
    }
{% endblock %}

{% block bloc1 %}
        <div class="col-md-4 info colonne">
            <div id="infojoueur">
                <div id="img">
                    <a href="{{ path("modifier_avatar") }}"><img src="{{ asset(joueur.UserImage) }}" alt=""></a>
                </div>
                <div id="joueur">
                    <h2>{{ joueur.Username }}</h2>
                    <p  id="modifier"><a href="{{ path("modifier_informations") }}">Modifier mes informations</a></p>
                </div>
            </div>


            <div id="stats">
                <h2>Statistiques</h2>
                <p>Nombre de parties jouées : {{ joueur.UserJouees }}</p>
                <p>Nombre de parties gagnées : {{ joueur.UserWin }}</p>
                <p>Nombre de parties perdues : {{ joueur.userJouees - joueur.UserWin }}</p>
                {% if joueur.userJouees != 0 %}
                    <p>Ratio : {{ ((joueur.UserWin / joueur.userJouees)|round(2, 'floor'))*100 }}% de victoire</p>
                {% endif %}
            </div>
        </div>
        <div class="col-md-4 info section">
            <h2>Amis</h2>
            {% for ami in amis %}
                {% if ami.IdAmi1 == joueur.Id %}
                        {% for tjoueurs in joueurs %}
                            {% if ami.IdAmi2 == tjoueurs.Id %}
                                <div id="ami">
                                    <a href="{{ path("joueur", {'id': tjoueurs.Id }) }}"><img class="avatars" src="{{ asset(tjoueurs.UserImage) }}" alt=""><p class="pseudojoueurs">{{  tjoueurs.Username }}<br/>Score : {{ tjoueurs.UserWin }}</p></a>
                                </div>

                                <hr>
                                {% endif %}
                        {% endfor %}
                {% endif %}
            {% endfor %}
            <p id="search" style="cursor:pointer;font-family: Cinzel;margin-bottom:1%;">Rechercher un joueur</p>
            <div id="searchbarre"><input id="inputsearch" type="text" placeholder="Pseudo joueur..."><button id="submitsearch">Rechercher</button></div>
            <div id="resultat"> </div>
        </div>
        <div class="col-md-4 info section">
        <h2>Classement</h2>
            {% set numero = 1 %}
        {% for i in 1000..0 %}
            {% for classement in rang %}
                {% if classement.UserWin == i %}
            <a href="{{ path("joueur", {'id': classement.Id }) }}">
                <img class="avatars" src="{{ asset(classement.UserImage)}}" alt=""><p class="position"># {{ numero }} : {{ classement.Username }}</p><br/>
                <p> Score : {{ classement.UserWin }}</p>
            </a>
                    <hr>
                    {% set numero = numero + 1 %}
                {% endif %}
            {% endfor %}
        {% endfor %}
        </div>
    <script>
        $(document).ready(function () {
            $('#search').click(function() {
                $('#search').hide(500);
                $('#searchbarre').show(500);
            });
            $('#submitsearch').click(function (){
               if($('#inputsearch').val() != ''){
                   var url = "{{ path('rechercher_joueur', {'username': 'text' }) }}";
                   var username = $('#inputsearch').val();
                   console.log(username);
                   url = url.replace("text", username);
                    console.log(url);
                   $('#resultat').load(url);
               }
            });
        });
    </script>

{% endblock %}